version: '3'

services:
  frontend:
    container_name: frontend_container
    image: {{ client_image }}
    ports:
      - 3000:3000
    networks:
       yolo-test-network:
        ipv4_address: 172.60.0.2

  backend:
    container_name: backend_container
    ports:
      - 5000:5000
    image: {{ backend_image }}
    environment:
      PORT: 3000
      MONGODB_URI: 'mongodb+srv://wnjenga:cwo1aYOmp7dr94Ky@cluster0.exzgxhs.mongodb.net/test'
    networks:
      backend-net:
        ipv4_address: 172.60.0.3
      frontend-net:
        ipv4_address: 172.60.0.4
    depends_on:
      - database
    volumes:
      - .:/app
  database:
    container_name: backend_database
    ports:
      - 27017:27017
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: backend
    networks:
      backend-net:
        ipv4_address: 172.100.0.101
    volumes:
        - backend_volume:/data/db
networks:
  backend-net:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
  frontend-net:
    ipam:
      driver: default
      config:
        - subnet: 172.60.0.0/16

volumes:
  backend_volume: